###############################################

# Run GitHub's Super Linter against code base #

###############################################


name: linter


on: push


jobs:

  run-linters:

    name: Linters

    runs-on: ubuntu-latest


    steps:

      - name: Check out Git repository

        uses: actions/checkout@master

        

      - name: GitHub Super-Linter

        uses: github/super-linter@main

        env:

          VALIDATE_ALL_CODEBASE: true

          DEFAULT_BRANCH: main

          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
